# Generated by Django 3.2.1 on 2021-05-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=256)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, choices=[('electronic_devices', 'Electronic Devices'), ('food', 'Food'), ('home_appliances', 'Home Appliances'), ('groceries', 'Groceries'), ('mens_Fashion', "Men's Fashion"), ('women_fashion', "Women's Fashion")], default='food', max_length=256, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('current_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('total_unit', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='super_shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line', to='super_shop.product')),
            ],
        ),
    ]
