# Generated by Django 3.2.1 on 2021-05-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
